/**
 * Template hash utilities for detecting user modifications
 *
 * Stores SHA256 hashes of template files at install time.
 * Used to determine if users have modified templates.
 *
 * Cross-platform contract:
 * - All hash dictionary keys are POSIX style (`/`), never `\`.
 * - Hashes are computed against LF-normalized content, so CRLF and LF
 *   versions of the same logical content produce the same hash.
 * - Persisted JSON uses schema `{ __version: 2, hashes: { ... } }`. Old
 *   flat-format files (no `__version`) are silently discarded; the hash
 *   set is regenerated on next init/update.
 */

import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { DIR_NAMES, FILE_NAMES } from "../constants/paths.js";
import { ALL_MANAGED_DIRS } from "../configurators/index.js";
import type { TemplateHashes } from "../types/migration.js";
import { toPosix } from "./posix.js";

/** File name for storing template hashes */
const HASHES_FILE = ".template-hashes.json";

/** Current schema version for `.template-hashes.json` */
const HASHES_SCHEMA_VERSION = 2;

/** Persisted shape of the hashes file (v2). */
interface StoredHashesV2 {
  __version: number;
  hashes: TemplateHashes;
}

/**
 * Compute SHA256 hash of content.
 *
 * Normalizes line endings (CRLF -> LF) before hashing so that the same
 * logical content yields the same hash across platforms.
 */
export function computeHash(content: string): string {
  const normalized = content.replace(/\r\n/g, "\n");
  return createHash("sha256").update(normalized, "utf-8").digest("hex");
}

/**
 * Get path to the hashes file
 */
function getHashesPath(cwd: string): string {
  return path.join(cwd, DIR_NAMES.WORKFLOW, HASHES_FILE);
}

/**
 * Normalize all keys of a hashes record to POSIX form.
 */
function normalizeHashKeys(hashes: TemplateHashes): TemplateHashes {
  const out: TemplateHashes = {};
  for (const [key, value] of Object.entries(hashes)) {
    out[toPosix(key)] = value;
  }
  return out;
}

/**
 * Load stored template hashes.
 *
 * Returns `{}` for: missing file, invalid JSON, or legacy flat-format
 * files (no `__version`). Legacy files are silently dropped; the hash
 * set is regenerated by subsequent init/update logic. This handles two
 * Windows compatibility issues at once: backslash keys and CRLF-based
 * hashes both differ from the v2 contract.
 */
export function loadHashes(cwd: string): TemplateHashes {
  const hashesPath = getHashesPath(cwd);
  if (!fs.existsSync(hashesPath)) {
    return {};
  }

  try {
    const content = fs.readFileSync(hashesPath, "utf-8");
    const parsed = JSON.parse(content) as unknown;

    if (
      parsed !== null &&
      typeof parsed === "object" &&
      "__version" in parsed &&
      (parsed as { __version: unknown }).__version === HASHES_SCHEMA_VERSION &&
      "hashes" in parsed &&
      typeof (parsed as { hashes: unknown }).hashes === "object" &&
      (parsed as { hashes: unknown }).hashes !== null
    ) {
      const stored = parsed as StoredHashesV2;
      // Defensive: enforce POSIX keys even if a writer slipped through.
      return normalizeHashKeys(stored.hashes);
    }

    // Legacy flat format (no __version) or unknown shape: discard.
    return {};
  } catch {
    return {};
  }
}

/**
 * Save template hashes.
 *
 * Always writes the v2 schema with POSIX-normalized keys.
 */
export function saveHashes(cwd: string, hashes: TemplateHashes): void {
  const hashesPath = getHashesPath(cwd);
  const payload: StoredHashesV2 = {
    __version: HASHES_SCHEMA_VERSION,
    hashes: normalizeHashKeys(hashes),
  };
  fs.writeFileSync(hashesPath, JSON.stringify(payload, null, 2));
}

/**
 * Update hashes for specific files
 *
 * @param cwd - Working directory
 * @param files - Map of relative paths to file contents
 */
export function updateHashes(cwd: string, files: Map<string, string>): void {
  const hashes = loadHashes(cwd);

  for (const [relativePath, content] of files) {
    hashes[toPosix(relativePath)] = computeHash(content);
  }

  saveHashes(cwd, hashes);
}

/**
 * Update hash for a single file by reading its current content
 */
export function updateHashFromFile(cwd: string, relativePath: string): void {
  const fullPath = path.join(cwd, relativePath);
  if (!fs.existsSync(fullPath)) {
    return;
  }

  const content = fs.readFileSync(fullPath, "utf-8");
  const hashes = loadHashes(cwd);
  hashes[toPosix(relativePath)] = computeHash(content);
  saveHashes(cwd, hashes);
}

/**
 * Remove hash entry for a file (e.g., after deletion)
 */
export function removeHash(cwd: string, relativePath: string): void {
  const hashes = loadHashes(cwd);
  const key = toPosix(relativePath);
  const { [key]: _, ...rest } = hashes;
  saveHashes(cwd, rest);
}

/**
 * Rename hash entry (used after file rename)
 */
export function renameHash(
  cwd: string,
  oldPath: string,
  newPath: string,
): void {
  const hashes = loadHashes(cwd);
  const oldKey = toPosix(oldPath);
  const newKey = toPosix(newPath);
  if (hashes[oldKey]) {
    const { [oldKey]: oldValue, ...rest } = hashes;
    rest[newKey] = oldValue;
    saveHashes(cwd, rest);
  }
}

/**
 * Check if a template file has been modified by the user
 *
 * @param cwd - Working directory
 * @param relativePath - Relative path to the file
 * @param hashes - Stored template hashes
 * @returns true if file has been modified from template, false otherwise
 */
export function isTemplateModified(
  cwd: string,
  relativePath: string,
  hashes: TemplateHashes,
): boolean {
  const fullPath = path.join(cwd, relativePath);

  // If file doesn't exist, can't be modified
  if (!fs.existsSync(fullPath)) {
    return false;
  }

  // If we don't have a stored hash, assume it's modified (conservative).
  // Lookup by POSIX key — hashes loaded via loadHashes are already
  // normalized, but the caller may have built `hashes` themselves.
  const posixKey = toPosix(relativePath);
  const storedHash = hashes[posixKey] ?? hashes[relativePath];
  if (!storedHash) {
    return true;
  }

  // Compare current content hash with stored hash
  const currentContent = fs.readFileSync(fullPath, "utf-8");
  const currentHash = computeHash(currentContent);

  return currentHash !== storedHash;
}

/**
 * Check if a file matches its original template content
 * (Useful for determining if a file can be safely auto-migrated)
 *
 * @param cwd - Working directory
 * @param relativePath - Relative path to the file
 * @param originalContent - Original template content
 * @returns true if file matches original template
 */
export function matchesOriginalTemplate(
  cwd: string,
  relativePath: string,
  originalContent: string,
): boolean {
  const fullPath = path.join(cwd, relativePath);

  if (!fs.existsSync(fullPath)) {
    return false;
  }

  const currentContent = fs.readFileSync(fullPath, "utf-8");
  return currentContent === originalContent;
}

/**
 * Get modification status for multiple files
 *
 * @param cwd - Working directory
 * @param relativePaths - Array of relative paths to check
 * @param hashes - Stored template hashes
 * @returns Map of path to modification status
 */
export function getModificationStatus(
  cwd: string,
  relativePaths: string[],
  hashes: TemplateHashes,
): Map<string, boolean> {
  const result = new Map<string, boolean>();

  for (const relativePath of relativePaths) {
    result.set(relativePath, isTemplateModified(cwd, relativePath, hashes));
  }

  return result;
}

/**
 * Directories to scan for template files during init (derived from platform registry)
 */
const TEMPLATE_DIRS = ALL_MANAGED_DIRS;

/** Root-level template files written by init and managed by update. */
const TEMPLATE_FILES = [FILE_NAMES.AGENTS] as const;

/**
 * Patterns to exclude from hash tracking
 */
const EXCLUDE_FROM_HASH = [
  ".template-hashes.json", // Hash file itself
  ".version", // Version file
  ".gitignore", // Git ignore files
  ".developer", // Developer identity file
  "workspace/", // Workspace files (user data)
  "tasks/", // Task files (user data)
  ".current-task", // Current task marker (file, not directory)
  ".trellis/spec/", // User-customized spec files
  ".trellis/user/", // User-facing project context docs
  ".backup-", // Backup directories
];

/**
 * Check if a path should be excluded from hash tracking
 */
function shouldExcludeFromHash(relativePath: string): boolean {
  const normalizedPath = toPosix(relativePath);
  for (const pattern of EXCLUDE_FROM_HASH) {
    if (normalizedPath.includes(pattern)) {
      return true;
    }
  }
  return false;
}

/**
 * Recursively collect all files in a directory.
 *
 * Returned paths are POSIX-normalized so they can be used directly as
 * hash dictionary keys regardless of host OS.
 */
function collectFiles(
  cwd: string,
  dir: string,
  relativeTo: string = "",
): string[] {
  const fullDir = path.join(cwd, dir);
  if (!fs.existsSync(fullDir)) {
    return [];
  }

  const files: string[] = [];
  const entries = fs.readdirSync(fullDir, { withFileTypes: true });

  for (const entry of entries) {
    const relativePath = path.join(dir, entry.name);

    if (shouldExcludeFromHash(relativePath)) {
      continue;
    }

    if (entry.isDirectory()) {
      files.push(...collectFiles(cwd, relativePath, relativeTo));
    } else if (entry.isFile()) {
      files.push(toPosix(relativePath));
    }
  }

  return files;
}

/**
 * Initialize template hashes after init
 *
 * Scans all template directories and computes hashes for files.
 * This should be called at the end of `trellis init` to enable
 * modification detection on subsequent updates.
 *
 * @param cwd - Working directory
 * @returns Number of files hashed
 */
export function initializeHashes(cwd: string): number {
  const hashes: TemplateHashes = {};

  for (const relativePath of TEMPLATE_FILES) {
    if (shouldExcludeFromHash(relativePath)) {
      continue;
    }

    const fullPath = path.join(cwd, relativePath);
    if (!fs.existsSync(fullPath)) {
      continue;
    }

    try {
      const content = fs.readFileSync(fullPath, "utf-8");
      hashes[relativePath] = computeHash(content);
    } catch {
      // Skip files that can't be read (binary, etc.)
    }
  }

  // Collect all template files
  for (const dir of TEMPLATE_DIRS) {
    const files = collectFiles(cwd, dir);

    for (const relativePath of files) {
      // `relativePath` is POSIX (collectFiles normalizes); reconstruct an
      // OS-native path for the actual fs read.
      const fullPath = path.join(cwd, relativePath);
      try {
        const content = fs.readFileSync(fullPath, "utf-8");
        hashes[relativePath] = computeHash(content);
      } catch {
        // Skip files that can't be read (binary, etc.)
      }
    }
  }

  saveHashes(cwd, hashes);
  return Object.keys(hashes).length;
}
